"""config.py

Central configuration dataclass for the entire Cart Abandonment ML pipeline.

This is the single source of truth for:
- Dataset generation parameters
- Preprocessing split ratios
- XGBoost hyperparameters (classifier + regressor)
- Artifact & model directory paths
- MLflow experiment tracking settings
- SHAP interpretability settings
- Evaluation thresholds
- Logging verbosity

Production rule: NO hyperparameters may be hardcoded anywhere else in the codebase.
All values must be sourced from this module.
"""

import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List

# Project root is two levels above this file: project_root/cart_abandonment_ml/config/config.py
_PROJECT_ROOT = Path(__file__).resolve().parents[2]


@dataclass
class XGBClassifierConfig:
    """Hyperparameters for the production XGBClassifier (target: cart_abandoned).

    This model uses predict_proba()[:,1] as the abandonment_probability output.
    """
    objective: str = "binary:logistic"
    eval_metric: str = "logloss"
    learning_rate: float = 0.05
    max_depth: int = 6
    n_estimators: int = 500
    subsample: float = 0.8
    colsample_bytree: float = 0.8
    min_child_weight: int = 5
    gamma: float = 0.1
    reg_alpha: float = 0.01
    reg_lambda: float = 1.0
    scale_pos_weight: float = 1.0          # Adjust for class imbalance if needed
    early_stopping_rounds: int = 30
    tree_method: str = "hist"              # CPU-optimised; switch to "gpu_hist" for GPU
    use_label_encoder: bool = False
    verbosity: int = 0


@dataclass
class XGBRegressorConfig:
    """Hyperparameters for the research XGBRegressor (target: abandonment_probability).

    Used for calibration comparison and research validation only.
    """
    objective: str = "reg:squarederror"
    eval_metric: str = "rmse"
    learning_rate: float = 0.05
    max_depth: int = 6
    n_estimators: int = 500
    subsample: float = 0.8
    colsample_bytree: float = 0.8
    min_child_weight: int = 5
    gamma: float = 0.1
    reg_alpha: float = 0.01
    reg_lambda: float = 1.0
    early_stopping_rounds: int = 30
    tree_method: str = "hist"
    verbosity: int = 0


@dataclass
class Config:
    """Central configuration for the Synthetic Data Generation and ML Pipeline."""

    # -------------------------------------------------------------------------
    # Global Settings
    # -------------------------------------------------------------------------
    RANDOM_SEED: int = 42
    N_SESSIONS: int = 500_000
    OUTPUT_DIR: str = str(_PROJECT_ROOT / "output")
    CSV_FILENAME: str = "synthetic_dataset.csv"
    PARQUET_FILENAME: str = "synthetic_dataset.parquet"

    # -------------------------------------------------------------------------
    # Data Source (generated by generate_synthetic_data.py)
    # -------------------------------------------------------------------------
    SYNTHETIC_PARQUET: str = str(_PROJECT_ROOT / "synthetic_cart_abandonment_500k.parquet")
    SYNTHETIC_CSV: str = str(_PROJECT_ROOT / "synthetic_cart_abandonment_500k.csv")

    # -------------------------------------------------------------------------
    # Preprocessing — split ratios
    # -------------------------------------------------------------------------
    TEST_SIZE: float = 0.10          # 10% test hold-out
    VAL_SIZE: float = 0.10           # 10% validation (of remaining 90%)

    # -------------------------------------------------------------------------
    # Artifact directories (absolute paths derived from project root)
    # -------------------------------------------------------------------------
    MODEL_DIR: str = str(_PROJECT_ROOT / "models")
    ARTIFACT_DIR: str = str(_PROJECT_ROOT / "artifacts")
    SHAP_DIR: str = str(_PROJECT_ROOT / "shap_output")
    PLOT_DIR: str = str(_PROJECT_ROOT / "plots")

    # -------------------------------------------------------------------------
    # Model hyperparameters (injected via sub-configs)
    # -------------------------------------------------------------------------
    CLASSIFIER: XGBClassifierConfig = field(default_factory=XGBClassifierConfig)
    REGRESSOR: XGBRegressorConfig = field(default_factory=XGBRegressorConfig)

    # -------------------------------------------------------------------------
    # Evaluation
    # -------------------------------------------------------------------------
    CLASSIFICATION_THRESHOLD: float = 0.41   # Probability cutoff for binary prediction
    CALIBRATION_N_BINS: int = 10             # Bins for reliability / calibration curve

    # -------------------------------------------------------------------------
    # SHAP interpretability
    # -------------------------------------------------------------------------
    SHAP_SAMPLE_SIZE: int = 5_000            # Rows used for global SHAP (speed vs accuracy)
    SHAP_MAX_DISPLAY: int = 20               # Top-N features shown in summary plots
    SHAP_TOP_FEATURES: int = 10              # Features returned by the prediction API

    # -------------------------------------------------------------------------
    # MLflow experiment tracking
    # -------------------------------------------------------------------------
    ENABLE_MLFLOW: bool = False  # Set True to enable experiment tracking via MLflow
    MLFLOW_TRACKING_URI: str = f"sqlite:///{(_PROJECT_ROOT / 'mlflow.db').as_posix()}"  # SQLite — MLflow 3.x requires a DB backend
    MLFLOW_EXPERIMENT_NAME: str = "cart_abandonment_prediction"

    # -------------------------------------------------------------------------
    # Gemini API (Root Cause Reasoning Agent)
    # -------------------------------------------------------------------------
    GEMINI_API_KEY: str = os.environ.get("GEMINI_API_KEY", "")  # Set via env var or override here
    GEMINI_MODEL_NAME: str = "gemini-2.0-flash"                 # Model used for root cause reasoning
    GEMINI_TEMPERATURE: float = 0.2                             # Low temp for deterministic reasoning
    GEMINI_MAX_OUTPUT_TOKENS: int = 1024

    # -------------------------------------------------------------------------
    # Logging
    # -------------------------------------------------------------------------
    LOG_LEVEL: str = "INFO"
    LOG_FORMAT: str = "[%(asctime)s] %(levelname)s %(name)s — %(message)s"

    # -------------------------------------------------------------------------
    # Persona Definitions and Mixture Probabilities (unchanged from original)
    # -------------------------------------------------------------------------
    PERSONAS: List[str] = field(default_factory=lambda: [
        "Price Sensitive Shopper",
        "Quality Conscious",
        "Loyal Customer",
        "Impulse Buyer",
        "Window Shopper",
        "Corporate Buyer",
        "First Time User",
        "Research Driven Buyer",
    ])

    PERSONA_PROBABILITIES: List[float] = field(default_factory=lambda: [
        0.20, 0.15, 0.10, 0.10, 0.15, 0.05, 0.10, 0.15
    ])

    # -------------------------------------------------------------------------
    # Missing Value Probabilities (unchanged from original)
    # -------------------------------------------------------------------------
    MISSING_RATES: Dict[str, float] = field(default_factory=lambda: {
        "user_age": 0.15,        # MNAR based on age > 50
        "location_tier": 0.05,  # MCAR
        "mouse_speed": 0.40,    # MAR based on device == Mobile/Tablet
    })

    # -------------------------------------------------------------------------
    # Noise Config (unchanged from original)
    # -------------------------------------------------------------------------
    IRRATIONAL_PURCHASE_RATE: float = 0.05
    IRRATIONAL_ABANDON_RATE: float = 0.07
    BOT_TRAFFIC_RATE: float = 0.02


# Module-level singleton — import this everywhere instead of instantiating manually
config = Config()
