import pandas as pd
import numpy as np
from .base_generator import BaseGenerator

class PricingGenerator(BaseGenerator):
    """Generates Price Intelligence and Discount metrics."""

    def generate(self, df: pd.DataFrame) -> pd.DataFrame:
        n = len(df)
        is_price_sens = df['persona'] == "Price Sensitive Shopper"
        
        # We need cart_value which is generated by CartGenerator, and discount_percentage from product metadata
        # Since product metadata is typically generated here, let's create it.
        df['discount_percentage'] = np.clip(np.random.normal(0.2, 0.15, size=n), 0, 0.9)
        df['total_discount_amount'] = df['cart_value'] * df['discount_percentage']
        
        df['coupon_error_count'] = np.random.poisson(lam=0.2, size=n)
        
        df['price_history_opened'] = (np.random.rand(n) < 0.05).astype(int)
        df.loc[is_price_sens, 'price_history_opened'] = (np.random.rand(is_price_sens.sum()) < 0.4).astype(int)
        
        # Proxying competitor checks using sequential behaviors if available
        # Tab switch and copy title features need to exist, or we mock them.
        df['tab_switch_count'] = np.random.poisson(lam=1.5, size=n)
        df.loc[df['persona'] == "Window Shopper", 'tab_switch_count'] += np.random.poisson(lam=5, size=(df['persona'] == "Window Shopper").sum())
        
        df['copy_product_title'] = (np.random.rand(n) < 0.05).astype(int)
        df.loc[is_price_sens, 'copy_product_title'] = (np.random.rand(is_price_sens.sum()) < 0.3).astype(int)
        
        df['competitor_price_checked'] = ((df['tab_switch_count'] > 2) & (df['copy_product_title'] == 1)).astype(int)
        df['competitor_difference'] = np.random.normal(0, 10, size=n) # Competitor is X% different
        
        # Product Metadata mapping logic commonly bundled with pricing
        df['product_rating'] = np.clip(np.random.normal(4.2, 0.6, size=n), 1.0, 5.0)
        df['rating_count'] = np.random.lognormal(mean=6, sigma=2, size=n).astype(int)
        df['return_policy_days'] = np.random.choice([0, 7, 10, 30], size=n, p=[0.1, 0.4, 0.3, 0.2])
        df['replacement_available'] = (np.random.rand(n) < 0.8).astype(int)
        
        # Reviews
        df['positive_reviews_read'] = np.random.poisson(lam=3, size=n)
        df['negative_reviews_read'] = np.random.poisson(lam=1, size=n)
        is_qual = df['persona'] == "Quality Conscious"
        df.loc[is_qual, 'negative_reviews_read'] += np.random.poisson(lam=4, size=is_qual.sum())
        df.loc[df['persona'] == "Research Driven Buyer", 'negative_reviews_read'] += 5
        
        return df
